---
abstract: 'Provide MongoDB connections, databases and collections'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Spec::Functions: 0
  File::Temp: 0
  IO::Handle: 0
  IPC::Open3: 0
  List::Util: 0
  Moose: 0
  Parallel::Iterator: 0
  Test::FailWarnings: 0
  Test::More: 0.96
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132620'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Role-MongoDB
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  MooseX::Role::MongoDB:
    file: lib/MooseX/Role/MongoDB.pm
    version: 0.001
requires:
  MongoDB::MongoClient: 0.702
  Moose::Role: 2
  MooseX::AttributeShortcuts: 0
  Type::Params: 0
  Types::Standard: 0
  namespace::autoclean: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/MooseX-Role-MongoDB/issues
  homepage: https://github.com/dagolden/MooseX-Role-MongoDB
  repository: https://github.com/dagolden/MooseX-Role-MongoDB.git
version: 0.001
x_authority: cpan:DAGOLDEN
